#!/usr/bin/env sh

OBJ="obj"
INCLUDE="-Isys/include"
CFLAGS="-g -m32 -ffreestanding -Wall -Wextra -pedantic -nostdlib $INCLUDE"
ASFLAGS="-felf32"
LDFLAGS="-m elf_i386"

mkdir -p $OBJ
rm -rf $OBJ/*

. boot/Makescript
. sys/Makescript

ld $LDFLAGS -T boot/link.ld -o omos $(for a in $OBJ/*; do printf "$a "; done)

echo "Build Success"
