#!/usr/bin/env sh

OBJ="obj"
INCLUDE="-Isys/drv/vga/include -Isys/include"
CFLAGS="-g -m32 -ffreestanding -Wall -Wextra -pedantic -nostdlib $INCLUDE"
ASFLAGS="-felf32"
LDFLAGS="-m elf_i386"

mkdir -p $OBJ

. boot/Makescript
. sys/Makescript
. sys/drv/Makescript

ld $LDFLAGS -T boot/link.ld -o omos obj/boot.o obj/vga.o obj/sysinit.o 

echo "Build Success"
